flaskblog/posts/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField as MyString, PasswordField as MyPassword, SubmitField as MySubmit, TextAreaField
from wtforms.validators import DataRequired as Required

  
class PostForm(Form):
    title = MyString('Title', validators=[Required()])
    content = TextAreaField('Content', validators=[Required()])
    submit = MySubmit('Post')

flaskblog/main/routes.py
from flask import Blueprint, render_template, request
from flaskblog.models import Post

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def homepage():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template('home.html', posts = posts)

@main.route('/about')
def about_page():
    return render_template('about.html', title = 'About')

@main.route('/announcements')
def announcements_page():
    return render_template('announcements.html', title = 'Announcements')

flaskblog/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm
from flask_login import login_user, current_user, logout_user, login_required


posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def newPost():
    form = PostForm()  # Initialize the form
    if form.validate_on_submit():  # Check if the form is submitted and valid
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)  # Add the new post to the database
        db.session.commit()  # Commit the changes to the database
        flash("Post Created!", 'success')  # Flash a success message
        return redirect(url_for('main.homepage'))  # Redirect to the homepage

    return render_template('newPost.html', title='New Post', form=form, legend='New Post')  # Render the template with form


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title='post.title', post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def updatePost(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Post Updated!", 'success')  # Flash a success message
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('newPost.html', title='Update post', form=form, legend='Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def deletePost(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()  # Commit the changes to the database
    flash("Post Deleted!", 'success')  # Flash a success message
    return redirect(url_for('main.homepage'))

flaskblog/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flaskblog.models import User, Post
from flaskblog import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog.users.forms import RegistrationForm, LogInForm, UpdateForm, RequestPasswordReset, PasswordReset, BioForm
from flaskblog.users.utils import save_image, sendPasswordReset
from flaskblog.posts.forms import  PostForm



users = Blueprint('users', __name__)


@users.route('/sign-up', methods=['GET', 'POST'])
def signUp():
    if current_user.is_authenticated:
        return redirect(url_for('main.homepage'))
    """flash works just like alert. it enables us to display a one time message to the user
    flash accepts a second argument which indicates if the message is a success error or so
    """
    form = RegistrationForm()
    if form.validate_on_submit():
        hashedPassword = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, email = form.email.data, password = hashedPassword)
        db.session.add(user)
        db.session.commit()
        flash("Account Created Successfully! Welcome on Board, {}".format(form.username.data), 'success')
        return redirect(url_for('users.signIn'))
    return render_template('signUp.html', title = 'Sign Up', form = form)

@users.route('/sign-in', methods=['GET', 'POST'])
def signIn():
    if current_user.is_authenticated:
        return redirect(url_for('main.homepage'))  
    form = LogInForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_password.data)
            nextPage = request.args.get('next')
            return redirect(nextPage) if nextPage else redirect(url_for('main.homepage'))
        else:
            flash("Invalid Email or Password!", 'danger')
    return render_template('signIn.html', title = 'Sign In', form = form)

@users.route('/sign-out')
def signOut():
    logout_user()
    return redirect(url_for('main.homepage'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateForm()
    if form.validate_on_submit():
        update_made = False

        # Check if the profile picture is being updated
        if form.picture.data:
            picture_file = save_image(form.picture.data)
            if current_user.profile_image != picture_file:
                current_user.profile_image = picture_file
                update_made = True

        # Check if username or email is being updated
        if form.username.data != current_user.username:
            current_user.username = form.username.data
            update_made = True
        
        if form.email.data != current_user.email:
            current_user.email = form.email.data
            update_made = True

        # Commit changes only if there are updates
        if update_made:
            db.session.commit()
            flash("Account Updated!", 'success')
        else:
            flash("No changes were made to your account.", 'info')
        
        return redirect(url_for('users.account'))
        
    elif request.method == 'GET':
        # Pre-fill the form with current user data
        form.username.data = current_user.username
        form.email.data = current_user.email

    # Generate the URL for the user's profile image
    userImage = url_for('static', filename='images/' + current_user.profile_image)
    return render_template('account.html', title='Account', userImage=userImage, form=form)



"""@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_image(form.picture.data)
             # Update the user's profile image
            current_user.profile_image = picture_file
            db.session.commit()  # Commit the changes before deleting old images
            # Delete the old images
            #delete_old_images(current_user) stop deleting for now.other users have their pp deleted when a new user uploades a pp
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Account Updated!", 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    userImage = url_for('static', filename='images/' + current_user.profile_image)
    return render_template('account.html', title = 'Account', userImage = userImage, form=form)"""
  
@users.route('/user/<string:username>')
def userPosts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template('userPosts.html', posts = posts, user=user)

def generate_summary(content, length=100):
    """Generate a summary from the content."""
    if len(content) > length:
        return content[:length] + '...'
    return content

@users.route('/latest-posts')
def latest_posts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)


    # Generate summaries dynamically
    for post in posts.items:
        post.summary = generate_summary(post.content)

    return render_template('latest_posts.html', posts=posts)


  
@users.route('/reset_password', methods=['GET', 'POST'])
def requestPasswordReset():
    if current_user.is_authenticated:
        return redirect(url_for('main.homepage'))

    form = RequestPasswordReset()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            token = user.get_reset_token(1800)
            sendPasswordReset(user)
            flash("An email has been sent to you! Follow the instructions to reset your password.", 'info')
        else:
            flash("If an account with that email exists, a reset link has been sent.", 'info')
        return redirect(url_for('users.signIn'))

    return render_template('requestPasswordReset.html', title='Reset Password', form=form)



@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def passwordReset(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.homepage'))
    user = User.verify_reset_token(token)
    if user is None:
        flash("Invalid or Expired Token!", 'warning')
        return redirect(url_for('users.requestPasswordReset'))
    form = PasswordReset()
    if form.validate_on_submit():
        hashedPassword = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashedPassword
        db.session.commit()
        flash("Your Password Has Been Updated! Welcome Back on Board, {}".format(user.username), 'success')
        return redirect(url_for('users.signIn'))
    return render_template('passwordReset.html', title='Reset Password', form=form)


@users.route('/bio', methods=['GET', 'POST'])
@login_required
def bio():
    user = current_user
    form = BioForm()
    
    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.commit()
        flash('Your bio has been updated.', 'success')
        return redirect(url_for('users.bio'))
    
    form.bio.data = user.bio
    return render_template('bio.html', user=user, form=form)

flaskblog/templates/about.html
{% extends "layout.html" %} {% block data %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 mx-auto">
      <div class="card shadow-sm">
        <div class="card-header bg-light text-white">
          <h2 class="mb-0">About Gadoski Blog</h2>
        </div>
        <div class="card-body">
          <p class="lead">
            Welcome to Gadoski Blog, a dynamic and user-friendly web blog
            platform designed to connect, share, and engage with a global
            audience. This platform provides a comprehensive suite of features
            to enhance your blogging experience and make it more enjoyable.
          </p>

          <h3 class="mt-4">Key Features:</h3>
          <ul class="list-group">
            <li class="list-group-item">
              <strong>Signup:</strong> Create a new account effortlessly.
            </li>
            <li class="list-group-item">
              <strong>Signin:</strong> Access your account securely with ease.
            </li>
            <li class="list-group-item">
              <strong>Create Post:</strong> Share your thoughts, ideas, and
              content with the world.
            </li>
            <li class="list-group-item">
              <strong>Update Post:</strong> Edit and update your existing posts
              to keep content relevant.
            </li>
            <li class="list-group-item">
              <strong>Delete Post:</strong> Remove posts you no longer wish to
              keep.
            </li>
            <li class="list-group-item">
              <strong>Add Profile Pictures:</strong> Personalize your profile
              with a custom image.
            </li>
            <li class="list-group-item">
              <strong>Reset Password:</strong> Securely reset your password if
              necessary.
            </li>
            <li class="list-group-item">
              <strong>See Other's Posts:</strong> Browse and engage with posts
              from other users.
            </li>

            <li class="list-group-item">
              <strong>Update Username and Email:</strong> Easily modify your
              account details to keep your profile up-to-date.
            </li>
          </ul>

          <h3 class="mt-4">Mission:</h3>
          <p>
            Here, my aim is to provide a platform that fosters creativity and
            connection. Whether you're a casual blogger or a seasoned writer,
            i'm committed to offering you the tools and support you need to
            succeed. My mission is to make blogging accessible and enjoyable for
            everyone.
          </p>

          <h3 class="mt-4">Contact Me:</h3>
          <p>
            If you have any questions, feedback, or need assistance, please feel
            free to reach out to me. You can contact me via email at
            <a href="mailto:gadoski321@gmail.com">support@gadoski.tech</a>.
          </p>
        </div>
        <div class="card-footer text-center bg-light">
          <div class="row">
            <div class="col-12 col-md-6 mb-2 mb-md-0">
              <a
                href="{{ url_for('main.homepage') }}"
                class="btn btn-primary btn-block"
              >
                Back to Homepage
              </a>
            </div>
            <div class="col-12 col-md-6">
              <a
                href="https://www.gadoski.tech/"
                class="btn btn-primary btn-block"
              >
                Back to Gadoski Tech
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock data %}

flaskblog/templates/account.html
{% extends "layout.html" %}

{% block data %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ userImage }}" />
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
    
    <form method="POST" action="" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-2">Account Info</legend>
        
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }}
          {% if form.username.errors %}
            {{ form.username(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        
        
        <div class="form-group">
          {{ form.picture.label }}
          {{ form.picture(class="form-control-file") }}
          {% if form.picture.errors %}
            {% for error in form.picture.errors %}
              <span class="text-danger">{{ error }}</span><br />
            {% endfor %}
          {% endif %}
        </div>
      </fieldset>
      
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock data %}

flaskblog/templates/bio.html
{% extends "layout.html" %}

{% block data %}
<h2>{{ user.username }}'s Bio</h2>

<form method="POST" action="{{ url_for('users.bio') }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <label for="bio">Bio</label>
        {{ form.bio(class="form-control") }}
    </div>
    <button type="submit" class="btn btn-primary">Update Bio</button>
</form>
<hr>
<p><strong>Your Bio:</strong> {{ user.bio }}</p>
{% endblock data %}

flaskblog/templates/home.html
{% extends "layout.html" %} {% block data %} {% for post in posts.items %}
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{ url_for('static', filename='images/' + post.author.profile_image) }}"
    alt="Profile Picture"
  />
  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{ url_for('users.userPosts', username=post.author.username) }}"
        >@{{ post.author.username }}</a
      >
      <small class="text-secondary"
        >{{ post.date_posted.strftime('%B %d, %Y at %H:%M %p') }}</small
      >
    </div>
    <h2>
      <a
        class="article-title"
        href="{{ url_for('posts.post', post_id=post.id) }}"
        >{{ post.title }}</a
      >
    </h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %} {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
left_current=2, right_current=2) %} {% if page_num %} {% if posts.page ==
page_num %}
<a
  class="btn btn-info mb-4"
  href="{{ url_for('main.homepage', page=page_num) }}"
  >{{ page_num }}</a
>
{% else %}
<a
  class="btn btn-outline-info mb-4"
  href="{{ url_for('main.homepage', page=page_num) }}"
  >{{ page_num }}</a
>
{% endif %} {% else %} ... {% endif %} {% endfor %} {% endblock data %}

flaskblog/templates/latest_posts.html
{% extends "layout.html" %} {% block data %}
<div class="container mt-4">
  <h1>Latest Posts</h1>

  {% if posts.items %}
  <ul class="list-group">
    {% for post in posts.items %}
    <li class="list-group-item">
      <a href="{{ url_for('posts.post', post_id=post.id) }}"
        >{{ post.title }}</a
      >
      <p>{{ post.summary }}</p>
    </li>
    {% endfor %}
  </ul>

  <!-- Pagination Controls -->
  <nav aria-label="Page navigation">
    <ul class="pagination">
      {% if posts.has_prev %}
      <li class="page-item">
        <a
          class="page-link"
          href="{{ url_for('main.latest_posts', page=posts.prev_num) }}"
          aria-label="Previous"
        >
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %} {% if posts.has_next %}
      <li class="page-item">
        <a
          class="page-link"
          href="{{ url_for('main.latest_posts', page=posts.next_num) }}"
          aria-label="Next"
        >
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% else %}
  <p>No posts available.</p>
  {% endif %}
</div>
{% endblock %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='main.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='styles.css') }}"
    />

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Home</title>
    {% endif %}
  </head>

  <body class="">
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-secondary fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Gadoski Blog</a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggle"
            aria-controls="navbarToggle"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.homepage') }}"
                >Home</a
              >
              <a
                class="nav-item nav-link"
                href="{{ url_for('main.about_page') }}"
                >About</a
              >
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('posts.newPost') }}"
                >New Post</a
              >
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}"
                >Account</a
              >
              <a class="nav-item nav-link" href="{{ url_for('users.signOut') }}"
                >Sign Out</a
              >
              {% else %}
              <a
                class="nav-item nav-link text-white"
                href="{{ url_for('users.signIn') }}"
                >Sign In</a
              >
              <a class="nav-item nav-link" href="{{ url_for('users.signUp') }}"
                >Sign Up</a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        {% if request.endpoint == 'main.homepage' %}
        <div class="col-md-4">
          <div class="content-section">
            {% if current_user.is_authenticated %}
            <h3>Hi, {{ current_user.username }}</h3>
            <p class="text-muted">
              {% if current_user.bio %}
                <p><strong></strong> {{ current_user.bio }}</p>
              {% else %}
                <p>You haven't added a bio yet. <a href="{{ url_for('users.bio') }}" class="mt-1">Create One Here</a></p>
              {% endif %}
            </p>
            {% else %}
            <h3>Hi There!</h3>
            <p class="text-muted">Sign In or Create a new account.</p>
            {% endif %}
            <ul class="list-group">
              <a
                class="list-group-item list-group-item-light"
                href="{{ url_for('users.userPosts', username=current_user.username) }}"
              >
                Your Posts
              </a>
              <a
                class="list-group-item list-group-item-light"
                href="{{ url_for('users.latest_posts') }}"
                >Latest Posts</a
              >
              <a
                class="list-group-item list-group-item-light"
                href="{{ url_for('main.announcements_page') }}"
                >Announcements</a
              >
              <a
                class="list-group-item list-group-item-light"
                href="https://www.gadoski.tech"
                >Back to Gadoski Tech</a
              >
            </ul>
          </div>
        </div>
        {% endif %}

        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories = true) %} {%
          if messages %} {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
          {% endfor %} {% endif %} {% endwith %} {% block data %}{% endblock
          data %}
        </div>
      </div>
    </main>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

flaskblog/templates/post.html
{% extends "layout.html" %} {% block data %}
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{ url_for('static', filename='images/' + post.author.profile_image) }}"
    alt="Profile Picture"
  />
  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{ url_for('users.userPosts', username=post.author.username) }}"
        >@{{ post.author.username }}</a
      >
      <small class="text-muted"
        >{{ post.date_posted.strftime('%B %d, %Y at %H:%M %p') }}</small
      >
      {% if post.author == current_user %}
      <div>
        <a
          class="btn btn-secondary btn-sm mt-2 mb-1"
          href="{{ url_for('posts.updatePost', post_id=post.id)}}"
          >Update</a
        >
        <button
          type="button"
          class="btn btn-danger btn-sm mt-2 m-1"
          data-toggle="modal"
          data-target="#deleteModal"
        >
          Delete
        </button>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title" href="#">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>

<!-- Modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <form
          action="{{ url_for('posts.deletePost', post_id=post.id)}}"
          method="POST"
        >
          <input class="btn btn-danger" type="submit" value="Delete" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock data %}

flaskblog/templates/signIn.html
{% extends "layout.html" %} {% block data %}
<div class="content-section mb-1">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-2">Sign In</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-lg
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span> {{ error }} </span>
          {% endfor %}
        </div>
        {% else%} {{ form.email(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span> {{ error }} </span>
          {% endfor %}
        </div>
        {% else%} {{ form.password(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-check">
        {{ form.remember_password(class="form-check-input") }}
        {{ form.remember_password.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
      <small class="text-muted">
      <a class="ml-2" href="{{ url_for('users.requestPasswordReset') }}">Reset Password</a>
  </small>
    </div>
  </form>
</div>
<div class="border-top pt-1">
  <small class="text-muted">
    Have no Account?
    <a class="ml-2" href="{{ url_for('users.signUp') }}">Create One Now</a>
  </small>
</div>
{% endblock data %}

flaskblog/templates/userPosts.html
{% extends "layout.html" %}
{% block data %}
  <h2 class="border border-2 border-gray mb-2 pl-1 pb-1">
    Posts By @{{ user.username }} ( 
    {{ posts.total }} {{ "post" if posts.total == 1 else "posts" }}
    )
  </h2>
{% for post in posts.items %}
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{ url_for('static', filename='images/' + post.author.profile_image) }}"
    alt="Profile Picture"
  />
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.userPosts', username=post.author.username) }}">@{{ post.author.username }}</a>
      <small class="text-secondary"
        >{{ post.date_posted.strftime('%B %d, %Y at %H:%M %p')
        }}</small
      >
    </div>
    <h2>
      <a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}"
        >{{ post.title }}</a
      >
    </h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
  {% if page_num %}
    {% if posts.page == page_num %}
      <a class="btn btn-info mb-4" href="{{ url_for('users.userPosts', username=user.username, page=page_num) }}">{{ page_num }}</a>
    {% else %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('users.userPosts', username=user.username, page=page_num) }}">{{ page_num }}</a>
    {% endif %}
  {% else %}
    ...
  {% endif %}
{% endfor %}
{% endblock data %}